@startuml

actor User

User -> Huntsman                : getActiveWindow( void )
User <- Huntsman                : GetActiveWindowResponse
User -> Huntsman                : setWindowParameter( PARAM )
User <- Huntsman                : setWindowParameterResponse
User -> Huntsman                :

@enduml