@startuml

actor User

User -> Huntsman            : setHunterAmount( unsigned )
User -> Huntsman            : setHunterHoundCount( unsigned )
Huntsman -> Huntsman        : enableHoundScaling( false )
User -> Huntsman            : setHunterHoundScale( double )
Huntsman -> Huntsman        : enableHoundScaling( true )
User -> Huntsman            : setHoundsFree( bool )

@enduml